### ISSUE TITLE
Under Development?

### ISSUE THREAD

**Issue by lalzz** [Camtendo/jokemon#3]
Is this project currently under any form of development?

**Comment by Camtendo** [comment]
Not currently. It's more of an archive at this point. If anyone wants to fork and add to it, they definitely can.

**Comment by Camtendo** [comment]
The game should already be feature complete and fully playable on Windows machines, for what it's worth. There may be a few bugs though.

**Comment by lalzz** [comment]
Ok I just wanted to know. I was planning on developing this with the intent of speeding up build times. The game is already highly functional.
